///|
#external
type DOMRect

///|
pub extern "js" fn DOMRect::get_x(self : Self) -> Double = "(self) => self.x"

///|
pub extern "js" fn DOMRect::get_y(self : Self) -> Double = "(self) => self.y"

///|
pub extern "js" fn DOMRect::get_width(self : Self) -> Double = "(self) => self.width"

///|
pub extern "js" fn DOMRect::get_height(self : Self) -> Double = "(self) => self.height"

///|
pub extern "js" fn DOMRect::get_top(self : Self) -> Double = "(self) => self.top"

///|
pub extern "js" fn DOMRect::get_right(self : Self) -> Double = "(self) => self.right"

///|
pub extern "js" fn DOMRect::get_bottom(self : Self) -> Double = "(self) => self.bottom"

///|
pub extern "js" fn DOMRect::get_left(self : Self) -> Double = "(self) => self.left"
